/**
 * Pizzara Coffee brand mark — the OFFICIAL logo bitmap (public/icons/logo.png,
 * served as the optimized 256px logo-ui.png generated by make-pwa-icons.mjs).
 * Transparent PNG of the espresso disc, so it sits on any background.
 */
export function PizzaraMark({ className }: { className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img src="/icons/logo-ui.png" alt="Pizzara Coffee" className={className} loading="lazy" />
  );
}
